const { NODEMAILER, SQS_EVENTS } = require('../../../config/constants');
const { sequelize } = require('../../models');

const send = async function (
  mailFrom,
  mailTo,
  mailSubject,
  mailBody,
  mailCc = '',
  mailBcc = '',
  attachments = []
) {
  try {
    let mailOptions = {
      to: mailTo,
      from: mailFrom,
      subject: mailSubject,
      attachments: attachments,
      html: mailBody,
      cc: mailCc ? mailCc : '',
      bcc: mailBcc ? mailBcc : '',
    };
    const SMTP_TRANSPORT = await NODEMAILER.createTransport({
      host: process.env.SMTP_HOST,
      port: process.env.SMTP_PORT,
      secure: false,
      auth: {
        user: process.env.SMTP_USER, //generated by Mailtrap
        pass: process.env.SMTP_PASS, //generated by Mailtrap
      },
      secure: process.env.SMTP_PORT === 465, // true for 465, false for other ports
    });
    // Sends email asynchronously and capturing the response
    SMTP_TRANSPORT.sendMail(mailOptions, async (err) => {
      console.log('err', err);

      // Handle the error if any and return the mailError exit route
      if (err) {
        return { isError: true, data: err.message || err };
      }
      console.log('mail sent!');
      // Mail has been sent successfully.
      if (type === SQS_EVENTS.MAIL.MAILBOX) {
        await addEmail(
          mailOptions,
          imapCreds,
          MAILBOX_STATUS.SENT,
          schema,
          shopId
        );
      }
    });
    return { isError: false, data: true };
  } catch (error) {
    return { isError: true, data: error.message || error };
  }
};

module.exports = { send };
